# Generated by Django 3.2.7 on 2022-01-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20220107_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ManyToManyField(to='taskapp.Item'),
        ),
    ]
