# Generated by Django 3.2.7 on 2022-01-08 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_task_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='item',
        ),
        migrations.AddField(
            model_name='task',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.item'),
        ),
    ]
