# Generated by Django 3.2.7 on 2022-01-08 03:20

from django.db import migrations, models
import taskapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_auto_20220108_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=taskapp.models.Task.default_date),
        ),
        migrations.RemoveField(
            model_name='task',
            name='item',
        ),
        migrations.AddField(
            model_name='task',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='taskapp.Item'),
        ),
    ]
