# Generated by Django 3.2.7 on 2022-01-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_auto_20220108_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ManyToManyField(blank=True, to='taskapp.Item'),
        ),
    ]
