# Generated by Django 3.2.7 on 2022-01-12 03:14

from django.db import migrations, models
import taskapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='item',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=taskapp.models.Task.default_date, null=True),
        ),
    ]
