# Generated by Django 3.2.7 on 2022-01-17 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_auto_20220112_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 20, 4, 4, 37, 861176, tzinfo=utc), null=True),
        ),
    ]
