# Generated by Django 3.2.7 on 2022-01-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0014_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
